SELECT
    A.APNT_NO AS APNTNO,
    P.PT_NAME AS PTNAME,
    P.PT_NO AS PTNO,
    D.MCDP_CD AS MCDPCD,
    D.DR_NAME AS DRNAME,
    A.APNT_YMD AS APNTYMD
FROM
    APPOINTMENT A
JOIN
    DOCTOR D
ON
    A.MDDR_ID = D.DR_ID
JOIN
    PATIENT P
ON
    A.PT_NO = P.PT_NO
WHERE
    DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND A.APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
ORDER BY
    A.APNT_YMD ASC
;