WITH FILTERED_CARS AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(*) >= 5
),
MONTHLY_RECORDS AS (
    SELECT
        DATE_FORMAT(START_DATE, '%m') AS MONTH,
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        AND CAR_ID IN (SELECT CAR_ID FROM FILTERED_CARS)
    GROUP BY
        DATE_FORMAT(START_DATE, '%Y-%m'),
        CAR_ID
)
SELECT
    MONTH,
    CAR_ID,
    RECORDS
FROM
    MONTHLY_RECORDS
ORDER BY
    MONTH ASC,
    CAR_ID DESC;
