WITH MAX_ECOLIS AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_ECOLI_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR
)
SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (M.MAX_ECOLI_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA AS E
JOIN
    MAX_ECOLIS AS M
ON 
    YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY
    YEAR ASC,
    YEAR_DEV ASC;