SELECT
    CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR
WHERE
    CAR_TYPE = '세단'
    AND (
        SELECT
            START_DATE
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
            AND START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
        LIMIT
            1
    ) IS NOT NULL
ORDER BY
    CAR_ID DESC
;