WITH TYPE_MAX_INFO AS (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM
        FISH_INFO
    WHERE
        LENGTH IS NOT NULL
    GROUP BY
        FISH_TYPE
)
SELECT
    I.ID,
    N.FISH_NAME,
    I.LENGTH
FROM
    FISH_INFO I
JOIN
    FISH_NAME_INFO N
ON
    I.FISH_TYPE = N.FISH_TYPE
JOIN
    TYPE_MAX_INFO T
ON
    I.FISH_TYPE = T.FISH_TYPE
    AND I.LENGTH = T.MAX_LENGTH
ORDER BY
    I.ID ASC;