WITH TOTAL_SCORES AS (
    SELECT
        G.EMP_NO,
        SUM(G.SCORE) AS TOTAL_SCORE
    FROM
        HR_GRADE AS G
    GROUP BY
        G.EMP_NO
)
SELECT
    T.TOTAL_SCORE AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM
    TOTAL_SCORES AS T
JOIN
    HR_EMPLOYEES AS E
ON
    T.EMP_NO = E.EMP_NO
WHERE
    T.TOTAL_SCORE = (SELECT MAX(TOTAL_SCORE) FROM TOTAL_SCORES)
ORDER BY
    E.EMP_NO ASC;
