SELECT
    I.INGREDIENT_TYPE,
    SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    FIRST_HALF F
JOIN
    ICECREAM_INFO I
ON
    I.FLAVOR = F.FLAVOR
GROUP BY
    I.INGREDIENT_TYPE
ORDER BY
    F.TOTAL_ORDER ASC;